openapi: 3.0.0
info:
  title: DataOps API
  version: 1.0.0
  description: 데이터셋 관리 및 분석 모델 API 명세

paths:
  /datasets/:
    get:
      summary: 전체 데이터셋 목록 조회
      responses:
        "200":
          description: 데이터셋 목록 반환
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Dataset"

  /datasets/{dataset_id}/:
    get:
      summary: 특정 데이터셋 상세 조회
      parameters:
        - name: dataset_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 데이터셋 상세 정보
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DatasetDetail"

components:
  schemas:
    Dataset:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        num_samples:
          type: integer
        labels:
          type: array
          items:
            type: string

    DatasetDetail:
      allOf:
        - $ref: "#/components/schemas/Dataset"
        - type: object
          properties:
            sample_records:
              type: array
              items:
                type: object
